language: node_js
node_js:
  - 12
deploy:
  provider: heroku
  api_key:
    secure: f3KQfdOAMSerUWH4FFlSBnXNpJ9eSBLPMPRUa9ObgJEQVZocVlsJpiqCLydC+gdLjFT5FJXCL9uJ7AHd3u0wNJ6g6/h3gdFiPAY+L4oSDIezeYBdHazSeo/EaoSKa8r7QmJqLGVXaxXLoBPI9G8w6/YMVZDENYMytnc11wdiPB/akp2dOkey71gHZ5mKMjYPYKU16/3S9MJKFPSX3UMkDknbHXFQ6yxGCfADMpDTMoD3m569LwoFclB7huYuw+HiyRsKJDdwUxRyurJBxtg9jHSA61q4Zim3b4BQlj4Z5Sz0kj4d9pSoZR11ZLIcZI1f2XtLTZJorQRkHwAlwmr2ARV4y7BC5f9EtuRnwAzJE50uYDiOaUSg7X7nFUw1t6iAUo+YVvgu+wjonNCWxHb12wtj5Okp+ljNbekhcJ3PkqZSr6XhXRCzfLDO9YbawBEOibpjhbDQ2aJwtZZuRPgBE4rEKgHCKfUeh5lRIvH51aDykgblDxREwQxRMJDlK5Ykv45J1nCcuncifvjrrTE4MEQHlsQ6+iFUtOiThcqdlnhZ+fIK6ygaehDyDvnZwZ8eUw5nE22MBZ18gDSdx6cum4CjWZmEpcmuQdPSFJI6tt/9lje5MZTs4uTVgTJgek/wB5hFpG9n8F5LK2fxlLkUYsELMuaMSftZ7MRXBTLT7mI=
  app: solo-development-web
  skip_cleanup: true
before_install:
  - openssl aes-256-cbc -K $encrypted_749dcc9e92f7_key -iv $encrypted_749dcc9e92f7_iv
    -in credentials.json.enc -out credentials.json -d
